linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  dupl:
    threshold: 200
  misspell:
    ignore-words:
      - statuser
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    disable-tags:
      - opinionated
    disabled-checks:
      - ifElseChain
  gocyclo:
    min-complexity: 25
  lll:
    line-length: 200
  govet:
    disable:
      - composites

issues:
  include:
    - EXC0002 # disable excluding of issues about comments from golint
  exclude:
    - "ST1000:" # at least one file in a package should have a package comment (stylecheck)
    - "G204:" # rule that command runs must be hard coded
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - exportloopref
        - funlen
        - gocyclo
        - gosec
        - lll
        - unparam
    - path: cmd/ # The cmd package contains a lot of descriptions that must be on a single long line
      linters:
        - lll
        - funlen
    - path: tools/
      linters:
        - gosec
