version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 200
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-tags:
      - opinionated
      disabled-checks:
        - ifElseChain
    gocyclo:
      min-complexity: 25
    govet:
      disable:
        - composites
    lll:
      line-length: 200
    misspell:
      ignore-rules:
        - statuser
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - exportloopref
          - funlen
          - gocyclo
          - gosec
          - lll
          - unparam
        path: _test\.go
      # The cmd package contains a lot of descriptions that must be on a single long line
      - linters:
          - funlen
          - lll
        path: cmd/
      - linters:
          - gosec
        path: tools/
      # at least one file in a package should have a package comment (stylecheck)
      - path: (.+)\.go$
        text: 'ST1000:'
      # rule that command runs must be hard coded
      - path: (.+)\.go$
        text: 'G204:'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
