before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: arm
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
      arm: ARM
      arm64: ARM64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: multi-gitter
    tap:
      owner: lindell
      name: homebrew-multi-gitter
    download_strategy: CurlDownloadStrategy.
    goarm: 6
    commit_author:
      name: Johan Lindell
      email: johan@lindell.me
    description: "Update multiple repositories in bulk."
    license: "MIT"
    test: |
      system "#{bin}/program version"
